title: "Shrill Shrestha"
email: shrill.shrestha@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Just Exploring!!!
# Root directory for your portfolio. On GitHub Pages, this is the name of your repository.
baseurl: "/"
# Protocol + hostname for your portfolio. On GitHub Pages, this is https://yourusername.github.io
url: "https://shrillshrestha.github.io" 
twitter_username: mlhacks
github_username: mlh-fellowship
form_url: "https://formspree.io/f/xrgodpqo"
social_image: "./assets/img/social-link.jpg"
social_image_alt: # Alt text for the link preview image
google_analytics_measurement_id: # G-XXXXXXXXXX

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
